<h1> List

In [49]:
list1 = [1, 2, 3]
print(type(list1))
print(list1[0], list1[-1])


list1[1] = 'str1'
print(list1) 

list2 = range(10)
print(list2)
print(type(list2)) 


list2 = list(list2) 
print(type(list2))
print(list2[2:4])
print(list2[2:])
print(list2[:2]) 
print(list2[:])
print(list2[::2]) 
print(list2[:-1]) 

list2[2:4] = [8, 9] # 슬라이스된 리스트에 새로운 리스트 할당
list2[2:5] = [8, 9] # ??
print(list2)


<class 'list'>
1 3
[1, 'str1', 3]
range(0, 10)
<class 'range'>
<class 'list'>
[2, 3]
[2, 3, 4, 5, 6, 7, 8, 9]
[0, 1]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[0, 1, 8, 9, 5, 6, 7, 8, 9]


<h1> for loop

In [3]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
    print(squares)


cat
dog
monkey
[0]
[0, 1]
[0, 1, 4]
[0, 1, 4, 9]
[0, 1, 4, 9, 16]


<h1>  function

In [4]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:        
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


In [5]:
def hello(name, loud=False):
    if loud:
        print ('HELLO, %s!' % name.upper())
    else:
        print ('Hello, %s' % name)

hello('Bob') # 출력 "Hello, Bob"
hello('Fred', loud=True)  # 출력 "HELLO, FRED!"


Hello, Bob
HELLO, FRED!


<h1> zip

In [103]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)
    

for x, y  in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]): #???
    print(x, y)


1 4 7
2 5 8
3 6 9


ValueError: too many values to unpack (expected 2)

<h1> __call__

In [10]:
class Helloworld():
    def __init__(self):
        pass
    
 
    
helloworld = Helloworld()


class Helloworld():
    def __init__(self):
        pass
    
    def __call__(self):
        print("hello world")
        
helloworld = Helloworld()

callable(helloworld)


True

In [9]:
class Helloworld():
    def __init__(self):
        pass
    
    def temp():
        print('test print')

Helloworld.temp() 

test print


In [13]:
import torch 
import torch.nn as nn

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()  #use parant’s __init__ func.
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)

    def forward(self, x):
        #Max pooling over a (2, 2) window        
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        return x

net = Net()
print(net)
callable(net)
#net(inputData)


Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
)


True

<h1> Numpy

In [14]:
import numpy as np 

a = np.array([1,2,3])

print( type(a))
print( a ) 
 
print( a.ndim )
print( a.shape)

print( a[0] , a[1], a[2])

a[0] = 5 

print( a)

<class 'numpy.ndarray'>
[1 2 3]
1
(3,)
1 2 3
[5 2 3]


In [15]:
b = np.array( [ [1,2,3],[4,5,6] ])

print(b.shape)
print( b.ndim)

print( b[0][0], b[1][0])

(2, 3)
2
1 4


In [16]:
a = np.zeros( (2,2))
print( a)

b = np.ones( (1,2))

print(b)

c = np.full( (2,2), 7)
print(c)

d = np.eye(3)
print(d)

e = np.random.random(( 2,2))

print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.15753421 0.2402244 ]
 [0.32595902 0.40522472]]


In [17]:
a = np.array( [[1,2,3],[4,5,6],[7,8,9]] )

b = a[  :2 , 1:3 ]
print( b)


[[2 3]
 [5 6]]


In [18]:
a = np.array([ [1,2,3,4],[5,6,7,8],[9,10,11,12]])

print( a.shape ) 

b = np.reshape(a, (2,6))
print( b)

(3, 4)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


<h1> Exercise 1

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [20]:
 

a = np.array([1,2,3,4,5,6,7,8,9])
b = np.array([1,3,5,7,9,6,8,8,0])


(array([0, 5, 7]),)

In [26]:
a = np.arange(9).reshape(3,3)


In [35]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [82]:
print( a[[1, 0, 2]])

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [67]:
tmp = np.arange(16).reshape(2,8)

In [68]:
tmp

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [77]:
print( tmp[:, [1, 0]])

[[1 0]
 [9 8]]


In [113]:
a = np.array( (3,-2, 2, -1, 3 ))
 

array([3, 2, 3])

# Tensor

In [42]:
import numpy as np 
import torch 

t1 = torch.FloatTensor( [0,1,2,3,4,5,6])
t2 = torch.tensor(np.arange(7))

print( t1)
print( t2)

print( t1.shape)
print( t2.shape)

tensor([0., 1., 2., 3., 4., 5., 6.])
tensor([0, 1, 2, 3, 4, 5, 6])
torch.Size([7])
torch.Size([7])


In [92]:
b = np.arange(7)
print( type(b) , type(t1)) 

<class 'numpy.ndarray'> <class 'torch.Tensor'>


In [96]:
tt = torch.tensor(b)
t_from =torch.from_numpy(b)
print( type(tt), type(t_from ))
print( tt )
print( t_from )

b[0]= -10
print( tt )
print( t_from )



<class 'torch.Tensor'> <class 'torch.Tensor'>
tensor([0, 1, 2, 3, 4, 5, 6])
tensor([0, 1, 2, 3, 4, 5, 6])
tensor([0, 1, 2, 3, 4, 5, 6])
tensor([-10,   1,   2,   3,   4,   5,   6])


In [98]:
t_to_np = t_from.numpy()
print( type(t_to_np))

<class 'numpy.ndarray'>


In [99]:
tt.shape

torch.Size([7])

In [100]:
t_to_np.shape


(7,)

# Broadcasting 

In [44]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])

print( m1)
print( m2 )

m1 = torch.FloatTensor( [[1,2]])
m2 = torch.FloatTensor([3])

print( m1)
print( m2 )
print( m1 + m2)


m1 = torch.FloatTensor( [[1,2]]) #2* 1 
m2 = torch.FloatTensor([[3] , [4]]) #1 * 2 


print( m1 + m2 )

tensor([[3., 3.]])
tensor([[2., 2.]])
tensor([[1., 2.]])
tensor([3.])
tensor([[4., 5.]])
tensor([[4., 5.],
        [5., 6.]])


In [45]:
 

print( '-------------------------')
print( '   mul vs matmul ')
print( '-------------------------')

m1 = torch.FloatTensor( [ [1,2], [3,4] ])
m2 = torch.FloatTensor( [ [1], [2]])

print( m1 * m2 ) 

print( 'shape of Matrix 1 : ', m1.shape)
print( ' Shape of Matirx 2 : ' , m2.shape)
print( m1.matmul(m2))

-------------------------
   mul vs matmul 
-------------------------
tensor([[1., 2.],
        [6., 8.]])
shape of Matrix 1 :  torch.Size([2, 2])
 Shape of Matirx 2 :  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [46]:
import torch 
import numpy as np 

t = torch.FloatTensor([[1,2] , [3,4]])

print( type( t ))
print( t.shape )


print( ' dim=0 : ', t.mean(dim=0))
print( ' dim=1 : ', t.mean(dim=1))

<class 'torch.Tensor'>
torch.Size([2, 2])
 dim=0 :  tensor([2., 3.])
 dim=1 :  tensor([1.5000, 3.5000])


<h1> view & reshape

In [47]:
import torch
import numpy as np 

t = np.arange(12).reshape(-1, 2, 3)

print(t.shape)
print( t)

floatT = torch.FloatTensor(t)
print( floatT.shape)

print( floatT.view([-1, 3]) ) 

(2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


In [48]:
#t = np.arange(24)
print( t.shape )

floatT = torch.FloatTensor(t)


#print( floatT.view([-1, 2, 3])[2:4, : , 1 ] )


(24,)
tensor([[13., 16.],
        [19., 22.]])


<h1> Exercise 2

In [104]:
import numpy as np
a = np.arange(24)
a = np.reshape(a, (2, 3, 4))

print( a.shape)
print( a)

(2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [105]:
floatT = torch.FloatTensor(t)

In [112]:
print(floatT.view([-1, 2, 3])[2:4, :, 1])

tensor([[13., 16.],
        [19., 22.]])


In [86]:
print(a[0, 1:3, 2:4])


[[ 6  7]
 [10 11]]


In [87]:
print(a[0:1, 1:3, 2:4])


[[[ 6  7]
  [10 11]]]
