<h1> autograd

In [2]:
import torch 

w = torch.tensor(1.0, requires_grad=True)



In [3]:
a = w*3

l = a**2

l.backward()

print(w.grad)
print('l을 w로 미분한 값은 {}'.format(w.grad))

tensor(18.)
l을 w로 미분한 값은 18.0


<h1> Exercise 1

In [5]:
import torch 
import numpy as np
import torch.nn as nn
import torch.nn.functional as F 
import torch.optim as optim

x_train = torch.FloatTensor([[0], [1], [1]])
y_train = torch.FloatTensor([[0], [1], [2]])

w = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([w, b] , lr = 0.01)

nb_epochs = 3000

for epoch in range( nb_epochs + 1):
    
    hypothesis = x_train * w + b 

    cost = torch.mean( (hypothesis - y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0 :
        print( 'Epoch {:5d}/{} w:{:.3f} b:{:.3f} cost: {:.3f}' 
              .format(epoch, nb_epochs, w.item(), b.item(), cost.item() ))
        

Epoch     0/3000 w:0.020 b:0.020 cost: 1.667
Epoch   100/3000 w:0.782 b:0.509 cost: 0.283
Epoch   200/3000 w:0.981 b:0.403 cost: 0.230
Epoch   300/3000 w:1.114 b:0.301 cost: 0.202
Epoch   400/3000 w:1.212 b:0.225 cost: 0.186
Epoch   500/3000 w:1.285 b:0.168 cost: 0.178
Epoch   600/3000 w:1.340 b:0.125 cost: 0.173
Epoch   700/3000 w:1.380 b:0.093 cost: 0.170
Epoch   800/3000 w:1.411 b:0.070 cost: 0.169
Epoch   900/3000 w:1.433 b:0.052 cost: 0.168
Epoch  1000/3000 w:1.450 b:0.039 cost: 0.167
Epoch  1100/3000 w:1.463 b:0.029 cost: 0.167
Epoch  1200/3000 w:1.472 b:0.022 cost: 0.167
Epoch  1300/3000 w:1.479 b:0.016 cost: 0.167
Epoch  1400/3000 w:1.485 b:0.012 cost: 0.167
Epoch  1500/3000 w:1.488 b:0.009 cost: 0.167
Epoch  1600/3000 w:1.491 b:0.007 cost: 0.167
Epoch  1700/3000 w:1.494 b:0.005 cost: 0.167
Epoch  1800/3000 w:1.495 b:0.004 cost: 0.167
Epoch  1900/3000 w:1.496 b:0.003 cost: 0.167
Epoch  2000/3000 w:1.497 b:0.002 cost: 0.167
Epoch  2100/3000 w:1.498 b:0.002 cost: 0.167
Epoch  220

In [9]:
import torch 
import numpy as np
import torch.nn as nn
import torch.nn.functional as F 
import torch.optim as optim

x_train = torch.FloatTensor([[73,80,75], [93,88,93], [89, 91, 90],[96,98,100],[73,66,70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

w = torch.zeros((3, 1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([w, b] , lr = 1e-5)

nb_epochs = 1000

for epoch in range( nb_epochs + 1):
    
    #hypothesis = x_train * w + b 
    hypothesis = x_train.matmul(w) + b 
    
    #cost = torch.mean( (hypothesis - y_train)**2)
    cost = F.mse_loss(hypothesis, y_train)
 
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0 :
        print( 'Epoch {:5d}/{} cost: {:.3f}' 
              .format(epoch, nb_epochs, cost.item() ))
        print( w.squeeze() ) 
        
      

Epoch     0/1000 cost: 29661.801
tensor([0.2940, 0.2936, 0.2974], grad_fn=<SqueezeBackward0>)
Epoch   100/1000 cost: 1.564
tensor([0.6735, 0.6610, 0.6762], grad_fn=<SqueezeBackward0>)
Epoch   200/1000 cost: 1.498
tensor([0.6789, 0.6550, 0.6768], grad_fn=<SqueezeBackward0>)
Epoch   300/1000 cost: 1.435
tensor([0.6843, 0.6491, 0.6773], grad_fn=<SqueezeBackward0>)
Epoch   400/1000 cost: 1.376
tensor([0.6894, 0.6434, 0.6778], grad_fn=<SqueezeBackward0>)
Epoch   500/1000 cost: 1.319
tensor([0.6945, 0.6379, 0.6783], grad_fn=<SqueezeBackward0>)
Epoch   600/1000 cost: 1.266
tensor([0.6994, 0.6326, 0.6787], grad_fn=<SqueezeBackward0>)
Epoch   700/1000 cost: 1.216
tensor([0.7042, 0.6273, 0.6791], grad_fn=<SqueezeBackward0>)
Epoch   800/1000 cost: 1.168
tensor([0.7089, 0.6223, 0.6795], grad_fn=<SqueezeBackward0>)
Epoch   900/1000 cost: 1.122
tensor([0.7135, 0.6173, 0.6798], grad_fn=<SqueezeBackward0>)
Epoch  1000/1000 cost: 1.079
tensor([0.7179, 0.6125, 0.6801], grad_fn=<SqueezeBackward0>)


In [8]:
import torch 
import numpy as np
import torch.nn as nn
import torch.nn.functional as F 
import torch.optim as optim

x_train = torch.FloatTensor([[73,80,75], [93,88,93], [89, 91, 90],[96,98,100],[73,66,70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

w = torch.zeros((3, 1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([w, b] , lr = 1e-5)
loss = nn.MSELoss() 

nb_epochs = 1000

for epoch in range( nb_epochs + 1):
    
    #hypothesis = x_train * w + b 
    hypothesis = x_train.matmul(w) + b 
    
    #cost = torch.mean( (hypothesis - y_train)**2)
    #cost = F.mse_loss(hypothesis, y_train)
    cost = loss(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    if epoch % 100 == 0 :
        print( 'Epoch {:5d}/{} cost: {:.3f}' 
              .format(epoch, nb_epochs, cost.item() ))
        print( w.squeeze() ) 
        
      

Epoch     0/1000 cost: 29661.801
tensor([0.2940, 0.2936, 0.2974], grad_fn=<SqueezeBackward0>)
Epoch   100/1000 cost: 1.564
tensor([0.6735, 0.6610, 0.6762], grad_fn=<SqueezeBackward0>)
Epoch   200/1000 cost: 1.498
tensor([0.6789, 0.6550, 0.6768], grad_fn=<SqueezeBackward0>)
Epoch   300/1000 cost: 1.435
tensor([0.6843, 0.6491, 0.6773], grad_fn=<SqueezeBackward0>)
Epoch   400/1000 cost: 1.376
tensor([0.6894, 0.6434, 0.6778], grad_fn=<SqueezeBackward0>)
Epoch   500/1000 cost: 1.319
tensor([0.6945, 0.6379, 0.6783], grad_fn=<SqueezeBackward0>)
Epoch   600/1000 cost: 1.266
tensor([0.6994, 0.6326, 0.6787], grad_fn=<SqueezeBackward0>)
Epoch   700/1000 cost: 1.216
tensor([0.7042, 0.6273, 0.6791], grad_fn=<SqueezeBackward0>)
Epoch   800/1000 cost: 1.168
tensor([0.7089, 0.6223, 0.6795], grad_fn=<SqueezeBackward0>)
Epoch   900/1000 cost: 1.122
tensor([0.7135, 0.6173, 0.6798], grad_fn=<SqueezeBackward0>)
Epoch  1000/1000 cost: 1.079
tensor([0.7179, 0.6125, 0.6801], grad_fn=<SqueezeBackward0>)


<h1> linear model 

In [9]:
class MRModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear( 3,1 )   #-> 맞는 숫자 채우기 
        
    def forward(self, x):
        return self.linear(x)

In [10]:
model = MRModel()
optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 500

for epoch in range(nb_epochs + 1):
    # H(x) 계산
    prediction = model(x_train)
    # cost 계산
    
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 개선
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 20번마다 로그 출력    
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))
  

Epoch    0/500 Cost: 22692.912109
Epoch    1/500 Cost: 7113.770996
Epoch    2/500 Cost: 2230.537842
Epoch    3/500 Cost: 699.903442
Epoch    4/500 Cost: 220.130249
Epoch    5/500 Cost: 69.746819
Epoch    6/500 Cost: 22.609676
Epoch    7/500 Cost: 7.834702
Epoch    8/500 Cost: 3.203477
Epoch    9/500 Cost: 1.751783
Epoch   10/500 Cost: 1.296692
Epoch   11/500 Cost: 1.154033
Epoch   12/500 Cost: 1.109261
Epoch   13/500 Cost: 1.095205
Epoch   14/500 Cost: 1.090752
Epoch   15/500 Cost: 1.089318
Epoch   16/500 Cost: 1.088817
Epoch   17/500 Cost: 1.088630
Epoch   18/500 Cost: 1.088531
Epoch   19/500 Cost: 1.088463
Epoch   20/500 Cost: 1.088397
Epoch   21/500 Cost: 1.088350
Epoch   22/500 Cost: 1.088286
Epoch   23/500 Cost: 1.088232
Epoch   24/500 Cost: 1.088177
Epoch   25/500 Cost: 1.088111
Epoch   26/500 Cost: 1.088044
Epoch   27/500 Cost: 1.087991
Epoch   28/500 Cost: 1.087932
Epoch   29/500 Cost: 1.087891
Epoch   30/500 Cost: 1.087817
Epoch   31/500 Cost: 1.087770
Epoch   32/500 Cost: 1.0

Epoch  335/500 Cost: 1.070745
Epoch  336/500 Cost: 1.070698
Epoch  337/500 Cost: 1.070650
Epoch  338/500 Cost: 1.070585
Epoch  339/500 Cost: 1.070533
Epoch  340/500 Cost: 1.070478
Epoch  341/500 Cost: 1.070427
Epoch  342/500 Cost: 1.070354
Epoch  343/500 Cost: 1.070313
Epoch  344/500 Cost: 1.070258
Epoch  345/500 Cost: 1.070193
Epoch  346/500 Cost: 1.070145
Epoch  347/500 Cost: 1.070093
Epoch  348/500 Cost: 1.070035
Epoch  349/500 Cost: 1.069982
Epoch  350/500 Cost: 1.069924
Epoch  351/500 Cost: 1.069885
Epoch  352/500 Cost: 1.069824
Epoch  353/500 Cost: 1.069767
Epoch  354/500 Cost: 1.069712
Epoch  355/500 Cost: 1.069653
Epoch  356/500 Cost: 1.069605
Epoch  357/500 Cost: 1.069550
Epoch  358/500 Cost: 1.069492
Epoch  359/500 Cost: 1.069426
Epoch  360/500 Cost: 1.069382
Epoch  361/500 Cost: 1.069327
Epoch  362/500 Cost: 1.069274
Epoch  363/500 Cost: 1.069218
Epoch  364/500 Cost: 1.069166
Epoch  365/500 Cost: 1.069108
Epoch  366/500 Cost: 1.069060
Epoch  367/500 Cost: 1.068984
Epoch  368